import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const hudClient = await readFile(new URL('../modules/threads/client/hud.lua', import.meta.url), 'utf8')
const app = await readFile(new URL('../web/src/App.jsx', import.meta.url), 'utf8')
const reticle = await readFile(new URL('../web/src/components/CombatReticle.jsx', import.meta.url), 'utf8')
const reticleCss = await readFile(new URL('../web/src/components/CombatReticle.css', import.meta.url), 'utf8')

test('weapon groups publish the requested dynamic reticle profiles', () => {
  assert.match(hudClient, /\[`GROUP_RIFLE`\]\s*=\s*'rifle'/)
  assert.match(hudClient, /automaticWeaponGroups\s*=\s*\{[\s\S]*\[`GROUP_SMG`\]\s*=\s*true[\s\S]*\[`GROUP_MG`\]\s*=\s*true[\s\S]*\[`GROUP_RIFLE`\]\s*=\s*true/)
  assert.match(hudClient, /weaponGroup == `GROUP_SHOTGUN`[\s\S]*return 'shotgun'/)
  assert.match(hudClient, /automaticWeaponHashes\s*=\s*\{[\s\S]*\[`WEAPON_APPISTOL`\]\s*=\s*true[\s\S]*\[`WEAPON_MINIGUN`\]\s*=\s*true/)
  assert.match(hudClient, /tazerWeaponHashes\s*=\s*\{[\s\S]*\[`WEAPON_STUNGUN`\]\s*=\s*true/)
  assert.match(hudClient, /homingWeaponHashes\s*=\s*\{[\s\S]*\[`WEAPON_HOMINGLAUNCHER`\]\s*=\s*true/)
  assert.match(hudClient, /rpgWeaponHashes\s*=\s*\{[\s\S]*\[`WEAPON_RPG`\]\s*=\s*true/)
  assert.match(hudClient, /return 'tazer'/)
  assert.match(hudClient, /return 'homing'/)
  assert.match(hudClient, /return 'rpg'/)
  assert.match(hudClient, /return 'single'/)
  assert.match(hudClient, /GetPedAccuracy\(ped\)/)
  assert.match(hudClient, /GetEntitySpeed\(ped\)/)
  assert.match(hudClient, /IsPedShooting\(ped\)/)
  assert.match(hudClient, /weaponAiming = IsAimCamActive\(\)/)
  assert.match(hudClient, /weaponBloom\s*=\s*weaponBloom/)
  assert.match(hudClient, /weaponReticleType\s*=\s*weaponReticleType/)
  assert.match(app, /weaponBloom=\{hudData\.weaponBloom\}/)
  assert.match(app, /weaponAiming=\{hudData\.weaponAiming\}/)
  assert.match(app, /weaponReticleType=\{hudData\.weaponReticleType\}/)
  assert.match(hudClient, /HideHudComponentThisFrame\(14\)/)
  assert.doesNotMatch(hudClient, /ShowHudComponentThisFrame\(14\)/)
  assert.match(hudClient, /HOMING_LAUNCHER_HASH/)
  assert.match(hudClient, /homingEquipped/)
  assert.match(app, /weaponReticleType !== 'homing'/)
  assert.match(reticle, /reticleType === 'automatic' \|\| reticleType === 'shotgun'/)
  assert.match(reticle, /showAuthenticReticle && usesRing && weaponAiming/)
  assert.match(reticle, /getRingReticleDiameter\(weaponBloom, reticleType\)/)
  assert.match(reticle, /getOpenReticleGap\(weaponBloom\)/)
  assert.match(reticle, /showTazer/)
  assert.match(reticle, /showRpg/)
  assert.match(reticle, /isHoming/)
  assert.doesNotMatch(reticle, /showHoming/)
  assert.match(reticle, /reticleType === 'single' && weaponAiming/)
  assert.match(reticle, /reticleType === 'tazer' && weaponAiming/)
  assert.match(reticle, /reticleType === 'rpg' && weaponAiming/)
  assert.match(reticle, /showClassicDot && weaponAiming && !isHoming/)
  assert.match(reticle, /combat-reticle-tazer/)
  assert.match(reticle, /combat-reticle-ring--rpg/)
  assert.doesNotMatch(reticle, /combat-reticle-homing/)
  assert.match(reticle, /getOpenReticleGap\(weaponBloom\)/)
  assert.match(reticle, /getRingReticleDiameter\(weaponBloom, 'tazer'\)/)
  assert.match(reticle, /getRingReticleDiameter\(weaponBloom, 'rpg'\)/)
  assert.doesNotMatch(reticle, /getRingReticleDiameter\(weaponBloom, 'homing'\)/)
  assert.doesNotMatch(reticle, /__dot/)
  assert.doesNotMatch(reticle, /__diamond/)
  assert.doesNotMatch(reticle, /__tick/)
  assert.doesNotMatch(reticle, /tazer__arm/)
})

test('local firearm damage maps to the three requested hitmarker meanings', () => {
  assert.match(hudClient, /AddEventHandler\('entityDamaged'/)
  assert.match(hudClient, /culprit ~= PlayerPedId\(\)/)
  assert.doesNotMatch(hudClient, /\(tonumber\(baseDamage\) or 0\) <= 0/)
  assert.match(hudClient, /if IsEntityAPed\(victim\) then/)
  assert.match(hudClient, /elseif IsEntityAVehicle\(victim\) then/)
  assert.match(hudClient, /VEHICLE_HITMARKER_COOLDOWN_MS = 350/)
  assert.match(hudClient, /kind = 'vehicle'/)
  assert.match(hudClient, /criticalHitBones\[bone\]/)
  assert.match(hudClient, /kind = 'critical'/)
  assert.match(hudClient, /IsPedDeadOrDying\(victim, true\)/)
  assert.match(hudClient, /kind = 'knockout'/)
  assert.match(hudClient, /kind = 'regular'/)
  assert.match(hudClient, /action = 'combat:hitmarker'/)
  assert.match(app, /case 'combat:hitmarker'/)
})

test('combat overlay stays transparent and cannot capture input', () => {
  assert.match(reticleCss, /\.combat-reticle-layer\s*\{[^}]*background:\s*transparent;/s)
  assert.match(reticleCss, /\.combat-reticle-layer\s*\{[^}]*pointer-events:\s*none;/s)
  assert.match(reticleCss, /\.combat-reticle-ring\s*\{[^}]*border:\s*1px solid/s)
  assert.match(reticleCss, /\.combat-reticle-open\s*\{[^}]*width:\s*calc\(34px \* var\(--es-ui-scale\)\)/s)
  assert.match(reticleCss, /\.combat-reticle-tazer__stroke/)
  assert.match(reticleCss, /\.combat-reticle-ring--rpg/s)
  assert.doesNotMatch(reticleCss, /\.combat-reticle-homing/)
  assert.doesNotMatch(reticleCss, /combat-reticle-(?:tazer|rpg|homing)__dot/)
  assert.doesNotMatch(reticleCss, /border:\s*calc\(2px/)
  assert.match(reticleCss, /\.combat-hitmarker\s*\{[^}]*width:\s*calc\(16px \* var\(--es-ui-scale\)\);/s)
  assert.match(reticleCss, /\.combat-hitmarker\s*\{[^}]*height:\s*calc\(16px \* var\(--es-ui-scale\)\);/s)
  assert.doesNotMatch(reticleCss, /(?:linear|radial|conic)-gradient\(/)
  assert.match(reticleCss, /\.combat-hitmarker--knockout\s*\{[^}]*#f5d142/s)
  assert.match(reticleCss, /\.combat-hitmarker--critical\s*\{[^}]*#ff3038/s)
  assert.match(reticleCss, /\.combat-hitmarker--vehicle\s*\{[^}]*rgba\(176, 182, 188, 0\.42\)/s)
})
