import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const testDir = path.dirname(fileURLToPath(import.meta.url))
const read = (...parts) => readFileSync(path.join(testDir, '..', ...parts), 'utf8')

const client = read('modules', 'weapons', 'client.lua')
const config = read('config', 'shared.lua')
const settings = read('modules', 'settings', 'client.lua')
const component = read('web', 'src', 'components', 'WeaponWheel.jsx')
const styles = read('web', 'src', 'components', 'WeaponWheel.css')

assert.match(config, /Config\.WeaponWheel\s*=\s*\{[\s\S]*?enabled\s*=\s*false/)
assert.match(settings, /hud_customWeaponWheel\s*=\s*'customWeaponWheel'/)
assert.match(settings, /label = 'Custom Weapon Wheel'/)
assert.match(client, /LoadResourceFile\(GetCurrentResourceName\(\), 'web\/dist\/weapons\/manifest\.json'\)/)
assert.match(client, /HasPedGotWeapon\(ped, weapon\.hash, false\)/)
assert.match(client, /GetWeapontypeGroup\(weaponHash\)/)
assert.match(client, /AmmoState = lib\.require\(.modules\.threads\.client\.ammo_state.\)/)
assert.match(client, /AmmoState\.resolve\(/)
assert.match(client, /GetMaxAmmoInClip\(ped, weapon\.hash, true\)/)
assert.match(client, /lastKnownClipByWeapon/)
assert.match(client, /state\.config\.enabled ~= true or not Nui\.isReady\(\)/)
assert.match(client, /IsPauseMenuActive\(\) or IsNuiFocused\(\)/)
assert.match(client, /state\.config\.allowInVehicles ~= true and IsPedInAnyVehicle/)
assert.match(client, /IsPedInParachuteFreeFall\(ped\) or IsPedSwimming\(ped\)/)
assert.match(client, /DisableControlAction\(0, openControl, true\)/)
assert.match(client, /DisableControlAction\(0, 1, true\)/)
assert.match(client, /DisableControlAction\(0, 2, true\)/)
assert.match(client, /DisableControlAction\(0, 12, true\)/)
assert.match(client, /DisableControlAction\(0, 13, true\)/)
assert.match(client, /state\.mouseSelectorX \+ \(deltaX \* sensitivity\)/)
assert.match(client, /state\.mouseSelectorY \+ \(deltaY \* sensitivity\)/)
assert.match(client, /GetDisabledControlNormal\(0, 13\)/)
assert.match(client, /GetDisabledControlNormal\(0, 12\)/)
assert.match(client, /TriggerScreenblurFadeIn\(120\.0\)/)
assert.match(client, /TriggerScreenblurFadeOut\(120\.0\)/)
assert.match(client, /state\.ownsScreenBlur = true/)
assert.match(client, /BLUR_DELAY_MS/)
assert.match(client, /state\.blurStarted/)
assert.match(client, /while IsScreenblurFadeRunning\(\) do Wait/)
assert.doesNotMatch(client, /IsScreenblurFadeRunning\(\) then return/)
assert.match(client, /SetCurrentPedWeapon\(ped, weapon\.hash, false\)/)
assert.match(client, /AddEventHandler\('onResourceStop'/)
assert.match(component, /SLOT_POSITIONS/)
assert.match(component, /state\.categories\.map/)
assert.doesNotMatch(component, /weapon-wheel__connector/)
assert.doesNotMatch(component, /weapon-wheel__slot-label/)
assert.doesNotMatch(component, /weapon-wheel__slot-count/)
assert.doesNotMatch(component, /weapon-wheel__hint/)
assert.doesNotMatch(styles, /(?:linear|radial|conic)-gradient\s*\(/i)
assert.doesNotMatch(styles, /weapon-wheel__connector/)
assert.doesNotMatch(styles, /occupied-glow/)
assert.match(styles, /\.weapon-wheel__slot\.is-equipped::before/)
assert.match(styles, /\.weapon-wheel__slot\.is-selected:not\(\.is-empty\)::before/)
assert.match(styles, /border-radius:\s*50%/)
assert.match(styles, /\.weapon-wheel\s*\{[\s\S]*background:\s*transparent/)
assert.match(styles, /pointer-events:\s*none/)
assert.match(styles, /width:\s*clamp\(96px, 7\.7vw, 300px\)/)
assert.match(styles, /height:\s*clamp\(64px, 8\.9vh, 195px\)/)
assert.match(styles, /--ammo-height:\s*clamp\(20px, 2\.22vh, 50px\)/)
assert.match(styles, /width:\s*clamp\(340px, 35\.5vw, 1400px\)/)
assert.match(styles, /height:\s*clamp\(260px, 48\.2vh, 1050px\)/)

console.log('weapon wheel contract: PASS')
