const BASE_SCENE_STATE = {
  visible: true,
  radarVisible: true,
  vehicleVisible: false,
  aircraftVisible: false,
  forceAircraftHud: false,
  vehicleIdentity: null,
  sniperScopeVisible: false,
  healthRecentlyDamaged: false,
  staminaRegenerating: false,
  inWater: false,
  underwater: false,
  floodWarningActive: false,
  floodWarningDetail: '',
  hurricaneWarningActive: false,
  hurricaneWarningDetail: '',
  dynamicWeatherShow: false,
  dynamicWeatherDisplay: '',
  dynamicWeatherSeason: '',
  dynamicWeatherForecastLine: '',
  dynamicWeatherWetLabel: '',
  dynamicWeatherNext: '',
  health: 100,
  armor: 50,
  stamina: 100,
  hunger: 100,
  thirst: 100,
  stress: 0,
  oxygen: 100,
  isArmed: false,
  weaponType: 'none',
  weaponIcon: null,
  weaponName: '',
  weaponUsesCharge: false,
  weaponChargeReady: true,
  weaponChargeProgress: 100,
  showCrosshair: false,
  gta6AuthenticWeaponHud: false,
  gta6ShowWeaponName: true,
  gta6VehicleIdentification: true,
  ammoClip: -1,
  ammoReserve: -1,
  waypointDist: -1,
  waypointUnit: '',
  voipTalking: false,
  radioTalking: false,
  cruiseActive: false,
  cruiseSpeed: 0,
  nosVisible: false,
  nosAmount: 0,
  nosActive: false,
}

export const HUD_DEV_SCENARIOS = [
  {
    id: 'classic-on-foot',
    code: 'BASE',
    label: 'Classic on foot',
    description: 'Standard status, location, voice, and waypoint HUD.',
    patch: {
      gta6HudEnabled: false,
      health: 92,
      armor: 48,
      stamina: 100,
      hunger: 74,
      thirst: 58,
      stress: 16,
      oxygen: 100,
      street: 'Vespucci Boulevard',
      zone: 'Del Perro',
      zoneCode: 'DELPE',
      heading: 268,
      postal: '821',
      postalDist: 184,
      waypointDist: 642,
      waypointUnit: 'm',
      voipConnected: true,
      voipRange: 'normal',
      voipProximity: 0.62,
    },
  },
  {
    id: 'gta6-explore',
    code: 'G6',
    label: 'GTA 6 exploration',
    description: 'Place discovery, compact waypoint, and contextual vitals.',
    patch: {
      gta6HudEnabled: true,
      gta6AuthenticWeaponHud: false,
      gta6VehicleIdentification: true,
      health: 78,
      armor: 24,
      stamina: 63,
      street: 'Vinewood Boulevard',
      zone: 'Vinewood',
      zoneCode: 'VINE',
      heading: 41,
      waypointDist: 418,
      waypointUnit: 'm',
    },
  },
  {
    id: 'gta6-combat',
    code: 'G6',
    label: 'GTA 6 combat',
    description: 'Authentic weapon lockup, reticle, damage, and stamina states.',
    patch: {
      gta6HudEnabled: true,
      gta6AuthenticWeaponHud: true,
      gta6ShowWeaponName: true,
      health: 64,
      healthRecentlyDamaged: true,
      armor: 32,
      stamina: 71,
      staminaRegenerating: true,
      isArmed: true,
      weaponType: 'firearm',
      weaponIcon: 'weapon_carbinerifle',
      weaponName: 'Carbine Rifle',
      ammoClip: 24,
      ammoReserve: 120,
      showCrosshair: true,
      street: 'Forum Drive',
      zone: 'Strawberry',
      zoneCode: 'STRAW',
      heading: 184,
    },
  },
  {
    id: 'gta6-vehicle',
    code: 'G6',
    label: 'GTA 6 vehicle intro',
    description: 'Vehicle marque, engine/fuel reveal, and navigation handoff.',
    vehicleIntro: true,
    patch: {
      gta6HudEnabled: true,
      gta6VehicleIdentification: true,
      vehicleVisible: true,
      speed: 36,
      rpm: 48,
      currentGear: '3',
      gears: 6,
      fuel: 68,
      hasFuelProvider: true,
      engineHealth: 84,
      engineState: true,
      belt: true,
      street: 'Great Ocean Highway',
      zone: 'Del Perro Beach',
      zoneCode: 'DELBE',
      heading: 316,
    },
  },
  {
    id: 'standard-driving',
    code: 'CAR',
    label: 'Standard driving',
    description: 'Speedometer, RPM, gear, cruise, belt, fuel, and NOS.',
    patch: {
      gta6HudEnabled: false,
      disableSpeedometer: false,
      vehicleVisible: true,
      speed: 86,
      rpm: 74,
      gears: 6,
      currentGear: '4',
      fuel: 43,
      hasFuelProvider: true,
      engineHealth: 77,
      engineState: true,
      cruiseActive: true,
      cruiseSpeed: 82,
      headlights: 2,
      belt: true,
      harness: false,
      nosVisible: true,
      nosAmount: 61,
      nosActive: false,
    },
  },
  {
    id: 'low-vitals',
    code: 'WARN',
    label: 'Low vitals',
    description: 'Critical health, broken armor, needs, stress, and oxygen.',
    patch: {
      gta6HudEnabled: false,
      health: 18,
      healthRecentlyDamaged: true,
      armor: 0,
      stamina: 21,
      hunger: 12,
      thirst: 9,
      stress: 91,
      oxygen: 14,
      inWater: true,
      underwater: true,
      voipConnected: true,
      voipTalking: true,
    },
  },
  {
    id: 'aircraft-emergency',
    code: 'AIR',
    label: 'Aircraft emergency',
    description: 'Flight instruments, engine tiers, hydraulics, rotor, and stall.',
    patch: {
      gta6HudEnabled: false,
      aircraftVisible: true,
      forceAircraftHud: true,
      altitude: 2480,
      altitudeAgl: 1130,
      airspeed: 142,
      aircraftHeading: 72,
      aircraftFuel: 19,
      aircraftHasFuelProvider: true,
      aircraftEngineHealth: 43,
      engines: [43, 67],
      aircraftGearDown: false,
      aircraftHasFixedGear: false,
      aircraftTailRotorHealth: 360,
      aircraftMainRotorHealth: 740,
      aircraftGearHealth: 680,
      aircraftIsHelicopter: true,
      aircraftStalled: true,
      aircraftHydraulicsHudEnabled: true,
      aircraftHydraulicsHealth: 410,
      street: 'New Empire Way',
      zone: 'Los Santos International',
      zoneCode: 'AIRP',
      heading: 72,
    },
  },
  {
    id: 'sniper-scope',
    code: 'OPTIC',
    label: 'Sniper scope',
    description: 'Scoped view with zoom, range, and steadiness telemetry.',
    patch: {
      gta6HudEnabled: false,
      sniperScopeVisible: true,
      sniperScopeWeapon: 'HEAVY SNIPER MK II',
      sniperScopeZoom: 7.5,
      sniperScopeRange: 486,
      sniperScopeSteadiness: 72,
      isArmed: true,
      weaponType: 'firearm',
      weaponIcon: 'weapon_heavysniper_mk2',
      weaponName: 'Heavy Sniper Mk II',
      ammoClip: 6,
      ammoReserve: 24,
    },
  },
  {
    id: 'severe-weather',
    code: 'WX',
    label: 'Severe weather',
    description: 'Forecast line plus flood and hurricane warning strips.',
    patch: {
      gta6HudEnabled: false,
      dynamicWeatherResourceAvailable: true,
      showDynamicWeather: true,
      dynamicWeatherShow: true,
      dynamicWeatherDisplay: 'THUNDER',
      dynamicWeatherSeason: 'SUMMER',
      dynamicWeatherForecastLine: 'Heavy rain moving east',
      dynamicWeatherWetLabel: 'Flood risk rising',
      dynamicWeatherNext: 'CLEARING 18 MIN',
      floodWarningActive: true,
      floodWarningDetail: 'Seek higher ground',
      hurricaneWarningActive: true,
      hurricaneWarningDetail: 'Evacuation advised',
      showHurricaneWarning: true,
      street: 'Bay City Avenue',
      zone: 'Vespucci',
      zoneCode: 'VESP',
      heading: 224,
    },
  },
]

export function createDevVehicleIdentity(entryId) {
  return {
    entryId,
    brand: 'Vapid',
    name: 'Dominator GT',
    archetype: 'dominator10',
    modelKey: 'dominator10',
    proceduralLogo: false,
    engineState: true,
    engineHealth: 84,
    fuel: 68,
  }
}

export function applyHudDevScenario(previous, scenarioId, vehicleEntryId = 1) {
  const scenario = HUD_DEV_SCENARIOS.find((candidate) => candidate.id === scenarioId)
  if (!scenario) return previous

  const next = {
    ...previous,
    ...BASE_SCENE_STATE,
    ...scenario.patch,
  }

  if (scenario.vehicleIntro) {
    next.vehicleIdentity = createDevVehicleIdentity(vehicleEntryId)
  }

  return next
}
