
export const HUD_LAYOUT_PRESETS = {
  classic: {
    label: 'Classic',
    theme: {
      surface: 'rgba(10, 14, 20, 0.48)',
      surfaceBorder: 'rgba(255, 255, 255, 0.12)',
      text: '#f8fafc',
      mutedText: 'rgba(226, 232, 240, 0.68)',
      indicatorAccent: '#60a5fa',
      speedometerAccent: '#22c55e',
      voipAccent: '#22c55e',
      ammo: '#a3e635',
      health: '#22c55e',
      armor: '#60a5fa',
      hunger: '#f59e0b',
      thirst: '#38bdf8',
      stress: '#ef4444',
      oxygen: '#06b6d4',
    },
    layout: {
      indicator: { anchor: 'top-center', offsetX: 0, offsetY: 10, variant: 'segmented' },
      statusCluster: { anchor: 'bottom-left', offsetX: 18, offsetY: 20, variant: 'stacked' },
      speedometer: { anchor: 'bottom-right', offsetX: 24, offsetY: 22 },
      ammo: { anchor: 'bottom-right', offsetX: 62, offsetY: 132, variant: 'stacked' },
      voip: { anchor: 'bottom-right', offsetX: 16, offsetY: 18, variant: 'minimal' },
      waypoint: { anchor: 'above-minimap', offsetX: 0, offsetY: 54, variant: 'pill' },
    },
    defaults: { statusIconShape: 'bar', fuelDisplayStyle: 'bar' },
  },
  street: {
    label: 'Street Racer',
    theme: {
      surface: 'rgba(8, 10, 14, 0.42)',
      surfaceBorder: 'rgba(34, 211, 238, 0.18)',
      text: '#e2e8f0',
      mutedText: 'rgba(203, 213, 225, 0.64)',
      indicatorAccent: '#f97316',
      speedometerAccent: '#22d3ee',
      voipAccent: '#fb7185',
      ammo: '#fb7185',
      health: '#34d399',
      armor: '#38bdf8',
      hunger: '#f97316',
      thirst: '#22d3ee',
      stress: '#fb7185',
      oxygen: '#818cf8',
    },
    layout: {
      indicator: { anchor: 'top-left', offsetX: 22, offsetY: 12, variant: 'glass' },
      statusCluster: { anchor: 'left-above-minimap', offsetX: 18, offsetY: 180, variant: 'rail' },
      speedometer: { anchor: 'bottom-center', offsetX: 0, offsetY: 18 },
      ammo: { anchor: 'top-right', offsetX: 32, offsetY: 28, variant: 'inline' },
      voip: { anchor: 'bottom-left', offsetX: 18, offsetY: 138, variant: 'minimal' },
      waypoint: { anchor: 'top-right', offsetX: 34, offsetY: 84, variant: 'pill' },
    },
    defaults: { statusIconShape: 'hexagon', fuelDisplayStyle: 'radial' },
  },
  dispatch: {
    label: 'Dispatch',
    theme: {
      surface: 'rgba(12, 16, 22, 0.56)',
      surfaceBorder: 'rgba(148, 163, 184, 0.18)',
      text: '#f8fafc',
      mutedText: 'rgba(203, 213, 225, 0.66)',
      indicatorAccent: '#f59e0b',
      speedometerAccent: '#38bdf8',
      voipAccent: '#f59e0b',
      ammo: '#f59e0b',
      health: '#10b981',
      armor: '#60a5fa',
      hunger: '#fbbf24',
      thirst: '#38bdf8',
      stress: '#ef4444',
      oxygen: '#06b6d4',
    },
    layout: {
      indicator: { anchor: 'top-right', offsetX: 22, offsetY: 12, variant: 'segmented' },
      statusCluster: { anchor: 'bottom-left', offsetX: 18, offsetY: 20, variant: 'stacked' },
      speedometer: { anchor: 'bottom-right', offsetX: 36, offsetY: 46 },
      ammo: { anchor: 'bottom-center', offsetX: 0, offsetY: 14, variant: 'inline' },
      voip: { anchor: 'bottom-right', offsetX: 16, offsetY: 16, variant: 'boxed' },
      waypoint: { anchor: 'top-center', offsetX: 0, offsetY: 68, variant: 'pill' },
    },
    defaults: { statusIconShape: 'square', fuelDisplayStyle: 'bar' },
  },
  ghost: {
    label: 'Ghost',
    theme: {
      surface: 'rgba(15, 23, 42, 0.32)',
      surfaceBorder: 'rgba(255, 255, 255, 0.10)',
      text: '#f8fafc',
      mutedText: 'rgba(226, 232, 240, 0.56)',
      indicatorAccent: '#cbd5e1',
      speedometerAccent: '#a7f3d0',
      voipAccent: '#cbd5e1',
      ammo: '#e2e8f0',
      health: '#4ade80',
      armor: '#93c5fd',
      hunger: '#fbbf24',
      thirst: '#67e8f9',
      stress: '#fb7185',
      oxygen: '#7dd3fc',
    },
    layout: {
      indicator: { anchor: 'top-center', offsetX: 0, offsetY: 10, variant: 'slim' },
      statusCluster: { anchor: 'bottom-center-left', offsetX: -220, offsetY: 18, variant: 'compact' },
      speedometer: { anchor: 'bottom-right', offsetX: 24, offsetY: 20 },
      ammo: { anchor: 'top-left', offsetX: 26, offsetY: 24, variant: 'inline' },
      voip: { anchor: 'top-right', offsetX: 24, offsetY: 22, variant: 'minimal' },
      waypoint: { anchor: 'top-center', offsetX: 0, offsetY: 54, variant: 'pill' },
    },
    defaults: { statusIconShape: 'circle', fuelDisplayStyle: 'radial' },
  },
}
