const STATION_ICON_FILES = Object.freeze({
  RADIO_01_CLASS_ROCK: 'RADIO_01_CLASS_ROCK.png',
  RADIO_02_POP: 'RADIO_02_POP.png',
  RADIO_03_HIPHOP_NEW: 'RADIO_03_HIPHOP_NEW.png',
  RADIO_04_PUNK: 'RADIO_04_PUNK.png',
  RADIO_05_TALK_01: 'RADIO_05_TALK_01.png',
  RADIO_06_COUNTRY: 'RADIO_06_COUNTRY.webp',
  RADIO_07_DANCE_01: 'RADIO_07_DANCE_01.jpg',
  RADIO_08_MEXICAN: 'RADIO_08_MEXICAN.png',
  RADIO_09_HIPHOP_OLD: 'RADIO_09_HIPHOP_OLD.webp',
  RADIO_11_TALK_02: 'RADIO_11_TALK_02.png',
  RADIO_12_REGGAE: 'RADIO_12_REGGAE.png',
  RADIO_13_JAZZ: 'RADIO_13_JAZZ.png',
  RADIO_14_DANCE_02: 'RADIO_14_DANCE_02.png',
  RADIO_15_MOTOWN: 'RADIO_15_MOTOWN.webp',
  RADIO_16_SILVERLAKE: 'RADIO_16_SILVERLAKE.webp',
  RADIO_17_FUNK: 'RADIO_17_FUNK.png',
  RADIO_18_90S_ROCK: 'RADIO_18_90S_ROCK.webp',
  RADIO_19_USER: 'RADIO_19_USER.svg',
  RADIO_20_THELAB: 'RADIO_20_THELAB.webp',
  RADIO_21_DLC_XM17: 'RADIO_21_DLC_XM17.webp',
  RADIO_22_DLC_BATTLE_MIX1_RADIO: 'RADIO_22_DLC_BATTLE_MIX1_RADIO.png',
  RADIO_23_DLC_XM19_RADIO: 'RADIO_23_DLC_XM19_RADIO.webp',
  RADIO_27_DLC_PRHEI4: 'RADIO_27_DLC_PRHEI4.png',
  RADIO_34_DLC_HEI4_KULT: 'RADIO_34_DLC_HEI4_KULT.webp',
  RADIO_35_DLC_HEI4_MLR: 'RADIO_35_DLC_HEI4_MLR.png',
  RADIO_36_AUDIOPLAYER: 'RADIO_36_AUDIOPLAYER.png',
  RADIO_37_MOTOMAMI: 'RADIO_37_MOTOMAMI.svg',
})

export const RADIO_STATION_ICON_COUNT = Object.keys(STATION_ICON_FILES).length

export function getRadioStationIconUrl(stationId) {
  if (typeof stationId !== 'string') return null
  const filename = STATION_ICON_FILES[stationId.toUpperCase()]
  return filename ? `./radio-icons/${filename}` : null
}
